### ISSUE TITLE
How to reduce runtime exception caused by DEADLINE_EXCEEDED?

### ISSUE THREAD

**Issue by wrujia** [googleapis/java-logging-logback#651]
Hi,
In production environment we met this runtime exception on cloud logging recently. (As a result we lost our logs for a few minutes)

```
java.lang.RuntimeException: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 49.999962934s. [remote_addr=logging.googleapis.com/142.251.42.170:443]
	at com.google.cloud.logging.LoggingImpl$9.onFailure(LoggingImpl.java:823)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:100)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:126)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:200)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 49.999962934s. [remote_addr=logging.googleapis.com/142.251.42.170:443]
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:203)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:197)
	at com.google.api.core.ApiFutures$ApiFunctionToGuavaFunction.apply(ApiFutures.java:240)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:223)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:211)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:124)
	... 31 more
Caused by: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 49.999962934s. [remote_addr=logging.googleapis.com/142.251.42.170:443]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:51)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	... 18 more
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 49.999962934s. [remote_addr=logging.googleapis.com/142.251.42.170:443]
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 10 more

```
Our app is running on google app engine, and for logging libraries we use with the following versions: 
com.google.cloud:google-cloud-logging-logback:0.121.14-alpha
com.google.cloud:google-cloud-logging:3.1.1

This error has occurred for multiple times so we are wondering if there is anything we can do to prevent losing logs due to this error.

We contacted gcp support and did some research. The conclusion was, we cannot know the exact cause of the error, while some issues mentioned that setting writeSynchronicity from ASYNC to SYNC may help.
Our first question is, can setting SYNC really help reduce the error? (The error suggest a time out; I suppose that the communication speed does not very by the synchronicity)

Another solution we can imagine is to extend the deadline. So our second question is, is there any way to pass a customized deadline to the logging library(in configuration or something)?

Hope to get some answers. Thank you.

**Comment by minherz** [comment]
> Our first question is, can setting SYNC really help reduce the error? (The error suggest a time out; I suppose that the communication speed does not very by the synchronicity)

Please, see #249. Configuring ingestion mode to be synchronous will lead to performance degradation in the log intensive applications but will guarantee that the calls will perform synchronously, which reduces a risk for timeout.

>Another solution we can imagine is to extend the deadline. So our second question is, is there any way to pass a customized deadline to the logging library(in configuration or something)?

The library does not support grpc customization.

I see that you use the version of the logback appender that is based on the (relatively) old version of the google-cloud-logging library (3.1.1). This version of the logging library had a bug (googleapis/java-logging#632). The bug was fixed in the version 3.4.0 of the library. I recommend to upgrade your logback library to the version that is using the google-cloud-logging version 3.4.0 or higher. The upgraded library will be able to batch multiple log ingestion requests together to decrease a load on the grpc channel, hence decreasing the chances to timeout.

**Comment by minherz** [comment]
I am closing this issue for now. Feel free to reopen it if you feel the answer is not satisfying.

**Comment by manansaraf16** [comment]
Just to add up on the above, we are using python 3.11 and google cloud logging v 3.9.0, but we are still facing this issue from time to time. Reducing the number of logs did reduce the number of occurrences for the above. Is there a way to permanently stop this error from happening, or to at least suppress it?
